# Generated by Django 4.2.7 on 2023-11-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0002_rename_datetime_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
                ('start_lesson', models.IntegerField(default=1)),
                ('end_lesson', models.IntegerField(default=10)),
                ('lesson_prefix', models.CharField(default='Lesson #', max_length=100)),
                ('lesson_suffix', models.CharField(default='.', max_length=100)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.subscription')),
            ],
        ),
    ]
