# Generated by Django 4.2.7 on 2023-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_report_teacher_alter_report_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='start_from_one',
            field=models.BooleanField(default=False),
        ),
    ]
