# Generated by Django 4.2.7 on 2023-11-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='datetime',
            new_name='date',
        ),
    ]
