# Generated by Django 4.2.7 on 2023-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='work_schedule',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
