# Generated by Django 4.2.7 on 2023-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_subject_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
