# Generated by Django 4.2.7 on 2023-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_range',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
