# Generated by Django 4.2.7 on 2023-11-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('lesson_price', models.IntegerField(default=0)),
                ('lesson_duration', models.IntegerField(default=60)),
                ('published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
